use std::path::{Path, PathBuf};

use regex::Regex;
use serde::Serialize;

use crate::enrich;
use crate::types::FunctionRecord;

/// Aeneas file marker: first line of any Aeneas-generated `.lean` file.
const AENEAS_MARKER: &str = "-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS";

/// Parse all Aeneas-generated `.lean` files in a project, returning function records.
pub fn parse_aeneas_project(lean_project: &Path) -> Result<Vec<FunctionRecord>, String> {
    let lean_files = find_aeneas_lean_files(lean_project)?;
    if lean_files.is_empty() {
        return Err(format!(
            "No Aeneas-generated .lean files found under {}",
            lean_project.display()
        ));
    }

    println!("Parsing {} Aeneas-generated file(s)...", lean_files.len());
    for f in &lean_files {
        println!("  {}", f.display());
    }

    let mut all_records = Vec::new();
    for file_path in &lean_files {
        let content = std::fs::read_to_string(file_path)
            .map_err(|e| format!("Failed to read {}: {e}", file_path.display()))?;
        let records = parse_lean_file(&content);
        all_records.extend(records);
    }

    Ok(all_records)
}

/// Scan a Lean project directory for Aeneas-generated `.lean` files,
/// parse them, and write a `functions.json` that probe-aeneas can consume.
pub fn generate_functions_json(lean_project: &Path, output: &Path) -> Result<(), String> {
    let all_records = parse_aeneas_project(lean_project)?;

    println!("  Parsed {} function entries", all_records.len());

    let output_json = FunctionsFileOutput {
        functions: all_records.iter().map(|r| r.into()).collect(),
    };

    let json = serde_json::to_string_pretty(&output_json)
        .map_err(|e| format!("Failed to serialize functions.json: {e}"))?;
    std::fs::write(output, format!("{json}\n"))
        .map_err(|e| format!("Failed to write {}: {e}", output.display()))?;

    println!("  Written to {}", output.display());
    Ok(())
}

/// Recursively find `.lean` files starting with the Aeneas marker.
fn find_aeneas_lean_files(dir: &Path) -> Result<Vec<PathBuf>, String> {
    let mut results = Vec::new();
    find_aeneas_lean_files_recursive(dir, &mut results)?;
    results.sort();
    Ok(results)
}

fn find_aeneas_lean_files_recursive(dir: &Path, out: &mut Vec<PathBuf>) -> Result<(), String> {
    let entries = std::fs::read_dir(dir)
        .map_err(|e| format!("Failed to read directory {}: {e}", dir.display()))?;

    for entry in entries {
        let entry = entry.map_err(|e| format!("Directory entry error: {e}"))?;
        let path = entry.path();

        if path.is_dir() {
            let name = path.file_name().unwrap_or_default().to_string_lossy();
            if name.starts_with('.') || name == "lake-packages" {
                continue;
            }
            find_aeneas_lean_files_recursive(&path, out)?;
        } else if path.extension().is_some_and(|ext| ext == "lean") && is_aeneas_generated(&path)? {
            out.push(path);
        }
    }
    Ok(())
}

fn is_aeneas_generated(path: &Path) -> Result<bool, String> {
    let content = std::fs::read_to_string(path)
        .map_err(|e| format!("Failed to read {}: {e}", path.display()))?;
    Ok(content.starts_with(AENEAS_MARKER))
}

/// A docstring block parsed from an Aeneas-generated definition.
#[derive(Debug)]
struct DocstringBlock {
    rust_name: Option<String>,
    source: Option<String>,
    line_start: Option<usize>,
    line_end: Option<usize>,
}

/// Parse a single Aeneas-generated `.lean` file and return function records.
fn parse_lean_file(content: &str) -> Vec<FunctionRecord> {
    let mut records = Vec::new();
    let mut current_namespace: Option<String> = None;
    let mut current_doc: Option<DocstringBlock> = None;
    let mut in_docstring = false;
    let mut docstring_buf = String::new();
    let mut pending_def = false;

    let re_rust_name = Regex::new(r"\[([^\]]+)\]").expect("valid regex");
    let re_source = Regex::new(r"Source:\s*'([^']*)'").expect("valid regex");
    let re_lines = Regex::new(r"lines\s+(\d+):\d+-(\d+):\d+").expect("valid regex");
    let re_def = Regex::new(r"^(?:def|abbrev)\s+(\S+)").expect("valid regex");
    let re_bare_def = Regex::new(r"^(?:def|abbrev)\s*$").expect("valid regex");
    let re_structure = Regex::new(r"^structure\s+(\S+)").expect("valid regex");
    let re_namespace = Regex::new(r"^namespace\s+(\S+)").expect("valid regex");
    let re_end = Regex::new(r"^end\s+(\S+)").expect("valid regex");

    for line in content.lines() {
        let trimmed = line.trim();

        // Handle continuation: `def` was on the previous line, name is on this line
        if pending_def {
            pending_def = false;
            let name_on_line = trimmed.split_whitespace().next();
            if let Some(name) = name_on_line {
                emit_record(name, &mut current_doc, &current_namespace, &mut records);
            }
            continue;
        }

        // Track namespace
        if let Some(caps) = re_namespace.captures(trimmed) {
            current_namespace = Some(caps[1].to_string());
            continue;
        }
        if let Some(caps) = re_end.captures(trimmed) {
            if current_namespace.as_deref() == Some(&caps[1]) {
                current_namespace = None;
            }
            continue;
        }

        // Accumulate docstrings
        if trimmed.starts_with("/--") {
            in_docstring = true;
            docstring_buf.clear();
            docstring_buf.push_str(trimmed);

            if trimmed.ends_with("-/") {
                in_docstring = false;
                current_doc = Some(parse_docstring(
                    &docstring_buf,
                    &re_rust_name,
                    &re_source,
                    &re_lines,
                ));
            }
            continue;
        }
        if in_docstring {
            docstring_buf.push('\n');
            docstring_buf.push_str(trimmed);
            if trimmed.ends_with("-/") {
                in_docstring = false;
                current_doc = Some(parse_docstring(
                    &docstring_buf,
                    &re_rust_name,
                    &re_source,
                    &re_lines,
                ));
            }
            continue;
        }

        // Skip attribute lines (carry docstring forward to the def that follows)
        if trimmed.starts_with("@[") {
            continue;
        }

        // Bare `def` / `abbrev` on its own line — name follows on the next line
        if re_bare_def.is_match(trimmed) {
            pending_def = true;
            continue;
        }

        // Match definition on a single line (def/abbrev/structure)
        let def_name = re_def
            .captures(line)
            .map(|c| c[1].to_string())
            .or_else(|| re_structure.captures(line).map(|c| c[1].to_string()));

        if let Some(name) = &def_name {
            emit_record(name, &mut current_doc, &current_namespace, &mut records);
        }
    }

    records
}

/// Create a FunctionRecord from a parsed definition name and its docstring.
fn emit_record(
    name: &str,
    current_doc: &mut Option<DocstringBlock>,
    current_namespace: &Option<String>,
    records: &mut Vec<FunctionRecord>,
) {
    if let Some(doc) = current_doc.take() {
        let lean_name = match current_namespace {
            Some(ns) => format!("{ns}.{name}"),
            None => name.to_string(),
        };

        let is_hidden = enrich::is_hidden_by_name(&lean_name);
        let is_artifact = enrich::is_extraction_artifact(&lean_name);

        records.push(FunctionRecord {
            lean_name,
            rust_name: doc.rust_name,
            source: doc.source,
            lines: match (doc.line_start, doc.line_end) {
                (Some(s), Some(e)) => Some(format!("L{s}-L{e}")),
                _ => None,
            },
            is_hidden,
            is_extraction_artifact: is_artifact,
        });
    }
}

/// Parse an accumulated docstring block into structured fields.
fn parse_docstring(
    doc: &str,
    re_rust_name: &Regex,
    re_source: &Regex,
    re_lines: &Regex,
) -> DocstringBlock {
    let rust_name = re_rust_name.captures(doc).map(|c| {
        let raw = c[1].to_string();
        // Strip trailing ':' if present (some docstrings have `[name]:`)
        raw.trim_end_matches(':').to_string()
    });

    let source = re_source.captures(doc).map(|c| c[1].to_string());

    let (line_start, line_end) = re_lines
        .captures(doc)
        .map(|c| {
            let s: usize = c[1].parse().unwrap_or(0);
            let e: usize = c[2].parse().unwrap_or(0);
            (Some(s), Some(e))
        })
        .unwrap_or((None, None));

    DocstringBlock {
        rust_name,
        source,
        line_start,
        line_end,
    }
}

// --- Output serialization ---

#[derive(Serialize)]
struct FunctionOutputRecord {
    lean_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    rust_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    source: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    lines: Option<String>,
    is_hidden: bool,
    is_extraction_artifact: bool,
}

impl From<&FunctionRecord> for FunctionOutputRecord {
    fn from(r: &FunctionRecord) -> Self {
        Self {
            lean_name: r.lean_name.clone(),
            rust_name: r.rust_name.clone(),
            source: r.source.clone(),
            lines: r.lines.clone(),
            is_hidden: r.is_hidden,
            is_extraction_artifact: r.is_extraction_artifact,
        }
    }
}

#[derive(Serialize)]
struct FunctionsFileOutput {
    functions: Vec<FunctionOutputRecord>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_simple_def() {
        let content = r#"-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [spqr]: function definitions
import Aeneas

namespace spqr

/-- [spqr::util::inz]:
    Source: 'src/util.rs', lines 7:0-13:1 -/
def util.inz (value : Std.U8) : Result Std.U8 := do
  ok value

end spqr
"#;
        let records = parse_lean_file(content);
        assert_eq!(records.len(), 1);
        assert_eq!(records[0].lean_name, "spqr.util.inz");
        assert_eq!(records[0].rust_name.as_deref(), Some("spqr::util::inz"));
        assert_eq!(records[0].source.as_deref(), Some("src/util.rs"));
        assert_eq!(records[0].lines.as_deref(), Some("L7-L13"));
        assert!(!records[0].is_hidden);
        assert!(!records[0].is_extraction_artifact);
    }

    #[test]
    fn parse_trait_impl_is_hidden() {
        let content = r#"-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
namespace spqr

/-- Trait implementation: [spqr::proto::{core::clone::Clone for spqr::proto::Foo}]
    Source: 'src/proto.rs', lines 10:0-12:1 -/
@[reducible, rust_trait_impl "core::clone::Clone<spqr::proto::Foo>"]
def proto.Foo.Insts.CoreCloneClone : core.clone.Clone proto.Foo := {
  clone := proto.Foo.Insts.CoreCloneClone.clone
}

end spqr
"#;
        let records = parse_lean_file(content);
        assert_eq!(records.len(), 1);
        assert_eq!(records[0].lean_name, "spqr.proto.Foo.Insts.CoreCloneClone");
        assert!(records[0].is_hidden);
    }

    #[test]
    fn parse_loop_body_is_artifact() {
        let content = r#"-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
namespace spqr

/-- [spqr::util::compare]: loop body 0:
    Source: 'src/util.rs', lines 28:4-30:5 -/
@[rust_loop_body]
def util.compare_loop.body
  (lhs : Slice Std.U8) : Result Unit := ok ()

end spqr
"#;
        let records = parse_lean_file(content);
        assert_eq!(records.len(), 1);
        assert!(records[0].is_extraction_artifact);
    }

    #[test]
    fn parse_structure_in_types() {
        let content = r#"-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
namespace spqr

/-- [spqr::encoding::gf::GF16]
    Source: 'src/encoding/gf.rs', lines 20:0-23:1 -/
structure encoding.gf.GF16 where
  value : Std.U16

end spqr
"#;
        let records = parse_lean_file(content);
        assert_eq!(records.len(), 1);
        assert_eq!(records[0].lean_name, "spqr.encoding.gf.GF16");
        assert_eq!(records[0].source.as_deref(), Some("src/encoding/gf.rs"));
        assert_eq!(records[0].lines.as_deref(), Some("L20-L23"));
    }

    #[test]
    fn parse_reducible_def_with_attrs() {
        let content = r#"-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
namespace spqr

/-- Trait implementation: [core::borrow::{core::borrow::Borrow<T> for &0 (T)}]
    Source: '/rustc/library/core/src/borrow.rs', lines 229:0-229:38
    Name pattern: [core::borrow::Borrow<&'0 @T, @T>] -/
@[reducible, rust_trait_impl "core::borrow::Borrow<&'0 @T, @T>"]
def Shared0T.Insts.CoreBorrowBorrow (T : Type) : core.borrow.Borrow T T := {
  borrow := Shared0T.Insts.CoreBorrowBorrow.borrow
}

end spqr
"#;
        let records = parse_lean_file(content);
        assert_eq!(records.len(), 1);
        // The first bracketed match is the rust name
        assert_eq!(
            records[0].rust_name.as_deref(),
            Some("core::borrow::{core::borrow::Borrow<T> for &0 (T)}")
        );
        assert_eq!(records[0].lean_name, "spqr.Shared0T.Insts.CoreBorrowBorrow");
        assert!(!records[0].is_hidden); // non-boilerplate .Insts. trait
    }

    #[test]
    fn parse_multiline_def() {
        let content = r#"-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
namespace spqr

/-- [spqr::{core::ops::arith::Add<&'a Foo, Bar> for &1 Baz}::add]:
   Source: 'src/mod.rs', lines 415:4-430:5 -/
def
  Shared0Baz.Insts.CoreOpsArithAddSharedAFooBar.add
  (self : Baz) (other : Foo) : Result Bar := ok ()

end spqr
"#;
        let records = parse_lean_file(content);
        assert_eq!(records.len(), 1);
        assert_eq!(
            records[0].lean_name,
            "spqr.Shared0Baz.Insts.CoreOpsArithAddSharedAFooBar.add"
        );
        assert_eq!(records[0].source.as_deref(), Some("src/mod.rs"));
        assert!(!records[0].is_hidden); // arithmetic .Insts. not boilerplate
    }

    #[test]
    fn parse_multiline_def_with_attrs() {
        let content = r#"-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
namespace spqr

/-- [spqr::{core::ops::arith::Sub<&'a Foo, Bar> for &1 Baz}]:
   Source: 'src/mod.rs', lines 434:0-453:1 -/
@[reducible]
def
  Shared0Baz.Insts.CoreOpsArithSubSharedAFooBar
  : core.ops.arith.Sub Baz Foo Bar := {
  sub := Shared0Baz.Insts.CoreOpsArithSubSharedAFooBar.sub
}

end spqr
"#;
        let records = parse_lean_file(content);
        assert_eq!(records.len(), 1);
        assert_eq!(
            records[0].lean_name,
            "spqr.Shared0Baz.Insts.CoreOpsArithSubSharedAFooBar"
        );
    }

    #[test]
    fn parse_global_simps_constant() {
        let content = r#"-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
namespace spqr

/-- [spqr::authenticator::{spqr::authenticator::Authenticator}::MACSIZE]
    Source: 'src/authenticator.rs', lines 34:4-34:39 -/
@[global_simps, irreducible]
def authenticator.Authenticator.MACSIZE : Std.Usize := 32#usize

end spqr
"#;
        let records = parse_lean_file(content);
        assert_eq!(records.len(), 1);
        assert_eq!(
            records[0].lean_name,
            "spqr.authenticator.Authenticator.MACSIZE"
        );
    }
}
